 -- PSQL / Oracle Database

CREATE USER ADMIN IDENTIFIED BY abcd1234;
GRANT CONNECT, RESOURCE TO ADMIN;
ALTER USER ADMIN QUOTA UNLIMITED ON USERS;

CONN SEU_USUARIO/SUA_SENHA;

CREATE TABLE PRODUCTS (
    ID NUMBER PRIMARY KEY,
    NAME VARCHAR2(100) NOT NULL,
    PRICE DECIMAL(10, 2) NOT NULL
);

INSERT INTO PRODUCTS (ID, NAME, PRICE) VALUES (1, 'Notebook', 2500.00);
INSERT INTO PRODUCTS (ID, NAME, PRICE) VALUES (2, 'Mouse', 150.50);
INSERT INTO PRODUCTS (ID, NAME, PRICE) VALUES (3, 'Teclado', 300.75);

COMMIT;


CREATE OR REPLACE PROCEDURE SP_GET_PRODUCT_PRICE (
    p_name IN PRODUCTS.NAME%TYPE,
    p_price OUT PRODUCTS.PRICE%TYPE
) AS
BEGIN
    SELECT PRICE
    INTO p_price
    FROM PRODUCTS
    WHERE NAME = p_name AND ROWNUM = 1;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        p_price := NULL;
END;
/

CREATE SEQUENCE SQ_PRODUCTS START WITH 4 INCREMENT BY 1;

CREATE OR REPLACE PROCEDURE SP_CREATE_PRODUCT (
    p_name IN PRODUCTS.NAME%TYPE,
    p_price IN PRODUCTS.PRICE%TYPE,
    p_new_id OUT PRODUCTS.ID%TYPE
) AS
BEGIN
    SELECT SQ_PRODUCTS.NEXTVAL INTO p_new_id FROM DUAL;

    INSERT INTO PRODUCTS (ID, NAME, PRICE)
    VALUES (p_new_id, p_name, p_price);

    COMMIT;
END;
/

